---
all:
  children:
    monitoring:
      hosts:
        uptime_kuma:
          ansible_host: localhost
          ansible_user: "{{ lookup('env', 'USER') }}"
          ansible_connection: local
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_user: root
          # ansible_become_password: "JOUW_SUDO_WACHTWOORD_HIER" # Optioneel

      vars:
        uptime_kuma_domain: localhost # Of IP van de VM
        uptime_kuma_port: 3001
        uptime_kuma_container_name: uptime-kuma
        enable_ssl: false
        email_address: your.email@example.com
        ansible_python_interpreter: /usr/bin/python3
        # ansible_ssh_common_args: "-o StrictHostKeyChecking=no" # Niet meer relevant
