---
all:
  children:
    monitoring:
      hosts:
        uptime_kuma:
          ansible_host: 157.90.255.248
          ansible_user: root
          ansible_ssh_private_key_file: private
          # ansible_become_password: "JOUW_SUDO_WACHTWOORD_HIER" # Optioneel

      vars:
        uptime_kuma_domain: 157.90.255.248 # Of IP van de VM
        uptime_kuma_port: 3001
        uptime_kuma_container_name: uptime-kuma
        enable_ssl: false
        email_address: your.email@example.com
        ansible_python_interpreter: /usr/bin/python3
        # ansible_ssh_common_args: "-o StrictHostKeyChecking=no" # Niet meer relevant
