---
# Docker installation tasks

- name: Add Docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: Install Docker packages
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create Docker compose directory
  file:
    path: /etc/docker/compose
    state: directory
    mode: '0755'

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add users to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  when: docker_users is defined

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Configure Docker log rotation
  template:
    src: docker-logrotate.conf.j2
    dest: /etc/logrotate.d/docker
    mode: '0644'

- name: Check if Docker network exists
  command: docker network inspect uptime-kuma-network
  register: network_check
  changed_when: false
  failed_when: false

- name: Create Docker network for Uptime Kuma
  command: docker network create uptime-kuma-network
  when: network_check.rc != 0 