---
- name: Install Fail2Ban
  ansible.builtin.package:
    name: fail2ban
    state: present
  when: fail2ban_enable

- name: Create Fail2Ban jail.local configuration
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  when: fail2ban_enable
  notify: restart fail2ban

- name: Ensure Fail2Ban is enabled and started
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
  when: fail2ban_enable
